### Signup

GET http://localhost:8080/tasks
# Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6InVzZXIiLCJzdWIiOiI0NGEzNzY4Yy1hMTI5LTQ4NWMtOGU1NS04Mzk5NWQxMTY2NGUiLCJlbWFpbCI6ImFzZGRAZ21haWwuY29tIiwiaWF0IjoxNjc2ODQ0ODcyLCJleHAiOjE2NzY4NDU3NzJ9.i-KJxhBLBHHb3LmXyPsz4aXlr-kO2Kgt0F3qFRyFjsk'

# {
#   "email": "asdd@gmail.com",
#   "password": "asd"
# }

